# Usa una imagen de Node.js basada en Alpine para reducir el tamaño del contenedor
FROM node:21-alpine3.19

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia los archivos de configuración de dependencias (package.json y pnpm-workspace.yaml)
COPY package.json pnpm-lock.yaml ./

# Instala pnpm globalmente
RUN npm install -g pnpm

# Instala las dependencias del proyecto (esto debe instalar las dependencias de todo el monorepo)
RUN pnpm install

# Copia el resto de los archivos del proyecto
COPY . .

# Expone el puerto en el que correrá la aplicación
EXPOSE 3001

# Comando por defecto para iniciar la aplicación
CMD ["pnpm", "run", "dev"]
